name = "asdro"
main = ".open-next/worker.js"
compatibility_date = "2026-06-09"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "asdro_db"
database_name = "asdro-db"
database_id = "8cd1fae2-5528-466c-adbb-d906f6029f9d"
